# Generated by Django 5.2.1 on 2025-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diciplina',
            new_name='Disciplina',
        ),
        migrations.RenameField(
            model_name='ambiente',
            old_name='diciplina',
            new_name='disciplina',
        ),
    ]
