# Generated by Django 5.2.1 on 2025-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_diciplina_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
